# Generated by Django 5.2.17 on 2026-09-04 08:10

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=80)),
                ("phone", models.CharField(max_length=18)),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "favorite_movie",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="account_email_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("age__gte", 14), ("age__lte", 100)),
                        name="account_age_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "token_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("expires_at", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.account"
                    ),
                ),
            ],
        ),
    ]
