# Generated by Django 5.2.17 on 2026-09-04 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_import_legacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.CharField(max_length=12)),
                ("text", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("request_id", models.UUIDField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portal.account",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["movie_id", "id"], name="comment_movie_cursor")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "request_id"), name="comment_request_unique"
                    )
                ],
            },
        ),
    ]
